### ISSUE TITLE
Chart not centered if simulator screen size is not the storyboard screen size

### ISSUE THREAD

**Issue by TDede** [ivnsch/PieCharts#44]
I'm using PieCharts within a StackView Controller. I designed my view for iPhone SE. When I use the view on a iPhone with a bigger screen than the SE (in extreme iPhone 8 plus) the pie chart is not centered anymore.

I tried a lot, but cannot center the chart. Is there a chance to do it, or do I have to work around.

**Comment by omegaes** [comment]
I have the same issue :\

**Comment by MrJorgeXavier** [comment]
Im having this issue too, and the work around i found was to add and configure the chart in code after the view layouts itself (viewDidAppear, for example).

**Comment by HelgaSokolova** [comment]
You don't need to remove it from storyboard. You just need to do all configurations(set layers, models) at `viewDidAppear()`, not `viewDidLoad()`.
I found this from the demo project.
